### PR TITLE
Allow max retries to be set on the callback

### PR DESCRIPTION
**Pull request by joonty**
Also update the ruby and bundler versions to modern numbers.

By default, Sidekiq will keep retrying endlessly when using `.delay`. You can turn off retries with `delay(retry: false)`, but you can't specify a number.

This change allows the maximum number of retries to be set via the `delayed_after_update` (or create) method as so:

```ruby
  delayed_after_update :failing_callback, retry_max: 3
```

If it's not set it will use the default behaviour of retrying indefinitely, but if it is set then the job will be rescheduled each time it fails (using a simple backoff) until the final attempt, when it's just left to fail.

### CODE REVIEW

**Comment by simonrentzke** [comment]
Wow. This ol' gem. Thanks Jon that looks great.

**Comment by joonty** [comment]
@simonrentzke I've had a bit of a nightmare with trying to get the tests to work. I got ruby version failures when trying to get backwards compatibility with rails 4, so I thought it would be best to ditch rails 4 support, which I think is fine considering it's long past EOL.

I tried adding Rails 6 to the Appraisals file, but ended up with incompatibility with the sqlite3 - Activerecord 5 requires sqlite3 1.3, and Activerecord 6 requires 1.4. Not sure if you know a way around that?

**Comment by simonrentzke** [comment]
@joonty I don't but you can just make it rails 6 supported if that easiest for you.

**Comment by joonty** [comment]
@simonrentzke cool, that's done.

**Pull request merged**
